[project]
name = "mids-207-project-chagas"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ecgmentations>=0.0.9",
    "numpy>=2.3.2",
    "scikit-learn>=1.7.1",
    "scipy>=1.16.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
